### ISSUE TITLE
Still valid?

### ISSUE THREAD

**Issue by assassin316** [moswald/RxUI-UWP-Sample#2]
Using the latest RxUI, is the BootstrapApplication class (and all it's related code) still necessary to get this working in a UWP app?

**Comment by moswald** [comment]
Honestly, I have no idea. I haven't had any UWP projects come my way in the last year. This was valid for the beta version of 7, so I _assume_ it's still a requirement of some kind. It's best to ask in the RxUI Slack channel, though.
